name: CI

on:
  schedule:
    # Run at AM 10:00 on every day-of-weak from Monday through Friday.
    - cron: 0 10 * * 1-5
  pull_request:

jobs:
  checks:
    name: Checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Check Spotless
        run: ./gradlew spotlessCheck
      - name: Check Compatibility
        run: ./gradlew apiCheck || { exit_code=$?; printf "*** This PR changes SDK's public API. If this change is intentional, run './gradlew apiDump' and commit the new API files. ***"; exit $exit_code; }
